### ISSUE TITLE
Printf cuts s-expressions sometime

### ISSUE THREAD

**Issue by evjava** [JetBrains-Research/Lama#18]
Code:
`printf("test: %s", GLOBAL ("x").string)`

expected: `test: GLOBAL ("x")`
actual: `test: GLOBA ("x")`

The same for `failure` and `sprintf`.

**Environment description**
OS: Ubuntu 18.04.5
opam version: 2.0.7
Lama version: {commit: 66dc5c30, date: 24.11.20}

**Comment by dboulytchev** [comment]
Not a bug; an implementation restriction --- only the first 5 symbols of constructors are taken into account.
