### ISSUE TITLE
Странное поведение с S-выражениями

### ISSUE THREAD

**Issue by kirindenle** [JetBrains-Research/Lama#19]
Матчится то, что не должно матчиться, имя S-выражения не совпадает, но паттерн матчится. Причём будет ли такой баг зависит от имени S-выражения.

Программа:
```
fun weirdCase (s) {
  case s of
      Binop (x) -> printf("weird 0\n")
    | _ -> printf("weird 1\n")
  esac
}

fun weirdCase2 (s) {
  case s of
      Abc (x) -> printf("weird 0\n")
    | _ -> printf("weird 1\n")
  esac
}

weirdCase(Binoprrr (100500));
weirdCase2(Abcrrr (100500))
```

Вывод:
```
weird 0
weird 1
```

**Comment by dboulytchev** [comment]
Not a bug; an implementation limitation. Added a section into the spec in 8bdd666ea829835c59f8a83b3660a3c4202f7d10.
