### ISSUE TITLE
Problem with Lama installation

### ISSUE THREAD

**Issue by BassinD** [JetBrains-Research/Lama#2]
Hi, I'm tried to install Lama through [intallation guide](https://github.com/JetBrains-Research/Lama#installation), but I couldn't complete last step with Lama package installation using opam.
I have the next output
<pre>$ opam pin add lama https://github.com/JetBrains-Research/Lama.git
<font color="#729FCF"><b>[NOTE]</b></font> Package lama is already git-pinned to
       https://github.com/JetBrains-Research/Lama.git.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[<font color="#4E9A06">lama</font>] https://github.com/JetBrains-Research/Lama.git updated
<font color="#CC0000">[ERROR]</font> File &quot;/home/bassid1/.opam/system/packages.dev/lama/opam&quot;, line 29,
        character 4-5: parse error.
<font color="#C4A000">[WARNING]</font> Errors in opam file from lama source, ignored (fix with &apos;opam pin
          edit&apos;)

<font color="#CC0000">[ERROR]</font> File &quot;/home/bassid1/.opam/system/overlay/lama/opam_&quot;, line 29,
        character 4-5: parse error.
Invalid opam file:
    <font color="#CC0000">error</font>  1: File does not parse
Errors in /home/bassid1/.opam/system/overlay/lama/opam, retry editing ? [Y/n] </pre>

The error is in the [opam file](https://github.com/JetBrains-Research/Lama/blob/1.00/opam) in the 29 line (4-5 character is space).
I tried to change space symbol to resolve encoding issue, but it didn't make sense.

**Environment description**
OS: Ubuntu 18.04
opam version: 1.2.2
ocaml version: 4.05.0
gcc-multilib version: 7.4.0

**Comment by dboulytchev** [comment]
Looks like a compatibility issue; try using fresher tools, in particular:

opam 2.0.4
ocaml 4.07.1

Perhaps you're installing them from Ubuntu's package repository, which is known for lagging behind.

**Comment by BassinD** [comment]
Yeah, it was compatibility issue.
I think adding minimal versions of required packages would be a good idea.
Thank you!
