### ISSUE TITLE
Typo in spec

### ISSUE THREAD

**Issue by GoPavel** [JetBrains-Research/Lama#20]
https://github.com/JetBrains-Research/Lama/blob/c83b153a1d35c361c49e2e348d1ed6c2a876e113/spec/04.extensions.tex#L50

I guess here should be:
```latex
 correspondingly, then importing  "\lstinline|A|" after  "\lstinline|B|" will result in "\lstinline|++|" having a \emph{lower} precedence, then 
```

**Comment by dboulytchev** [comment]
Fixed in 8bdd666ea829835c59f8a83b3660a3c4202f7d10.
