### ISSUE TITLE
Docker Image with Lama.

### ISSUE THREAD

**Issue by IlyasYOY** [JetBrains-Research/Lama#3]
Hello, I've built the language in docker, so anyone can just download the image and start using it!

```bash
➜  ~ docker run -it ilyasyoy/lama:1.0.0
opam@9dfa13e1da10:~/opam-repository$ cd Lama/tutorial/
opam@9dfa13e1da10:~/opam-repository/Lama/tutorial$ lamac Expressions.lama -o main && ./main 
if, case, for, while, repeat etc. are all expressions.
Case-expression: 3
If-expression: 
Scope-expression: 45
opam@9dfa13e1da10:~/opam-repository/Lama/tutorial$
```

[Here](https://hub.docker.com/r/ilyasyoy/lama) is the page on docker.hub.

I've also posted a **Dockerfile** [here](https://gist.github.com/IlyasYOY/816f819a5eca5a2632f213f0c62d1d43).

You can build it yourself and post it in GitHub packages so it'll be easier to find!

**Comment by dboulytchev** [comment]
Please make this a **PR** (not an issue) in README.md to https://github.com/dboulytchev/compiler-2020
