### ISSUE TITLE
Unable to installs lama following instructions

### ISSUE THREAD

**Issue by fstiffo** [JetBrains-Research/Lama#9]
Ubuntu 20.04
Opam 2.0.5
OCaml 4.10.0

**opam pin add -n ostap https://github.com/dboulytchev/ostap.git#memoCPS**

**[ostap.0.4] no changes from git+https://github.com/dboulytchev/ostap.git#memoCPS
ostap is now pinned to git+https://github.com/dboulytchev/ostap.git#memoCPS (version 0.4)**

**opam pin add -y lama https://github.com/JetBrains-Research/Lama.git**

**[lama.1.0] no changes from git+https://github.com/JetBrains-Research/Lama.git
lama is now pinned to git+https://github.com/JetBrains-Research/Lama.git (version 1.0)**

**Sorry, no solution found: there seems to be a problem with your request.**

**Comment by dboulytchev** [comment]
Is it still relevant? Sorry, I missed the notification for some reason.

**Comment by fstiffo** [comment]
I dropped it, but after your answer I will try to install it again. If there will be any problems I will update you.
